import os
from collections import OrderedDict
import numpy as np

from qtpy import QtWidgets, QtCore
import pytest
from pytest import fixture, approx
import qt_themes
from pymodaq.control_modules import daq_move as daqmv
from pymodaq.control_modules.daq_move import DAQ_Move, _to_module_params, _FLAT_PER_CHANNEL
from pymodaq.control_modules.move_utility_classes import HW_SETTINGS_KEY as ACTUATOR_SETTINGS_KEY
from pymodaq.control_modules.ct_module import ControllerThreadModule
from pymodaq.control_modules.utils import ControlModule

from pymodaq_utils.config import GlobalConfig

from pymodaq.utils.data import DataActuator

config = GlobalConfig()
config_viewer = config['pymodaq', 'viewer']


@fixture
def init_qt(qtbot):
    return qtbot


@fixture
def ini_daq_move_without_ui(init_qt):
    qtbot = init_qt
    prog = DAQ_Move()
    return prog, qtbot


@fixture
def ini_daq_move_ui(init_qt):
    qtbot = init_qt
    widget = QtWidgets.QWidget()
    qtbot.addWidget(widget)
    qt_themes.set_theme(theme=config('gui', 'style', 'theme')[0],
                        style=config('gui', 'style', 'style')[0])

    prog = DAQ_Move(widget)
    widget.show()
    yield prog, qtbot, widget
    widget.close()


class TestMantatoryAttributes:
    def test_methods(self, ini_daq_move_without_ui):
        actuator, qtbot = ini_daq_move_without_ui
        assert 'units' in actuator.__dir__()
        assert hasattr(actuator, 'title')


class TestMethods:
    def test_overriden(self):
        assert ControlModule.stop_grab != DAQ_Move.stop_grab
        assert ControlModule.grab != DAQ_Move.grab
        assert ControlModule.quit_fun != DAQ_Move.quit_fun
        assert ControlModule.init_hardware != DAQ_Move.init_hardware


class TestDAQMove:
    def test_data_emit(self, ini_daq_move_ui):
        daq_move, qtbot, widget = ini_daq_move_ui
        daq_move.actuator = 'Mock'

        with qtbot.waitSignal(daq_move.init_signal, timeout=10000) as blocker:
            daq_move.init_hardware_ui(True)
        assert blocker.args[0] is True

        POSITION = 34.5
        TIMEOUT = int(2 * daq_move.settings[ACTUATOR_SETTINGS_KEY, 'tau'])
        with qtbot.waitSignal(daq_move.move_done_signal, timeout=TIMEOUT) as blocker:
            with qtbot.waitSignal(daq_move.current_value_signal, timeout=1000) as val_blocker:
                daq_move.move_abs(POSITION)
        assert isinstance(val_blocker.args[0], DataActuator)
        assert val_blocker.args[0].name == daq_move.title

        data = blocker.args[0]
        assert isinstance(data, DataActuator)

        assert data.value() == pytest.approx(POSITION,
                                             abs=daq_move.epsilon)
        assert data.name == daq_move.title

        daq_move.quit_fun()
        QtWidgets.QApplication.processEvents() #make sure to properly terminate all the threads!

    def test_axis_management(self, ini_daq_move_ui):
        daq_move, qtbot, widget = ini_daq_move_ui
        daq_move.actuator = 'Mock'
        pass


# ---------------------------------------------------------------------------
# _to_module_params (pure Python, no Qt)
# ---------------------------------------------------------------------------

def _p(name, children=None, **kw):
    """Build a minimal param dict for testing."""
    d = {'name': name, 'type': 'str', **kw}
    if children is not None:
        d['children'] = children
    return d


def _flat_plugin_params(with_axis=True):
    """Minimal flat param list as generated by old comon_parameters_fun."""
    ctrl_children = [_p('controller_ID', type='int'), _p('controller_status')]
    if with_axis:
        ctrl_children.append(_p('axis', type='list'))
    return [
        _p('controller', children=ctrl_children),
        _p('units'),
        _p('epsilon'),
        _p('timeout'),
        _p('bounds', children=[_p('is_bounds'), _p('min_bound'), _p('max_bound')]),
        _p('scaling', children=[_p('use_scaling'), _p('scaling'), _p('offset')]),
        _p('com_port'),          # plugin-specific hardware param
    ]


def _flat_plugin_params_multiaxis(axis_names=None):
    """Minimal flat param list for a multi-axis old-style plugin (axis with limits)."""
    names = axis_names or ['x', 'y']
    ctrl_children = [
        _p('controller_ID', type='int'),
        _p('controller_status'),
        _p('axis', type='list', limits=names, value=names[0]),
    ]
    return [
        _p('controller', children=ctrl_children),
        _p('units'),
        _p('epsilon'),
        _p('timeout'),
        _p('bounds', children=[_p('is_bounds'), _p('min_bound'), _p('max_bound')]),
        _p('scaling', children=[_p('use_scaling'), _p('scaling'), _p('offset')]),
        _p('com_port'),
    ]


class TestToModuleParams:
    """_to_module_params converts old flat plugin params to the grouped layout."""

    def test_axis_settings_group_created(self):
        result = _to_module_params(_flat_plugin_params())
        names = [p['name'] for p in result]
        assert 'axis_settings' in names

    def test_per_channel_names_absent_at_top_level(self):
        result = _to_module_params(_flat_plugin_params())
        top_names = {p['name'] for p in result}
        assert top_names.isdisjoint(_FLAT_PER_CHANNEL)

    def test_per_channel_params_inside_axis_settings(self):
        result = _to_module_params(_flat_plugin_params())
        group = next(p for p in result if p['name'] == 'axis_settings')
        child_names = {c['name'] for c in group['children']}
        assert _FLAT_PER_CHANNEL.issubset(child_names)

    def test_axis_moved_from_controller_into_axis_settings(self):
        result = _to_module_params(_flat_plugin_params(with_axis=True))
        # axis_settings must contain axis
        group = next(p for p in result if p['name'] == 'axis_settings')
        child_names = [c['name'] for c in group['children']]
        assert 'axis' in child_names
        assert child_names[0] == 'axis'   # axis is first in the group

    def test_axis_first_in_axis_settings(self):
        result = _to_module_params(_flat_plugin_params(with_axis=True))
        group = next(p for p in result if p['name'] == 'axis_settings')
        assert group['children'][0]['name'] == 'axis'

    def test_controller_id_stays_in_controller(self):
        result = _to_module_params(_flat_plugin_params())
        ctrl = next(p for p in result if p['name'] == 'controller')
        ctrl_child_names = {c['name'] for c in ctrl['children']}
        assert 'controller_ID' in ctrl_child_names

    def test_axis_removed_from_controller(self):
        result = _to_module_params(_flat_plugin_params(with_axis=True))
        ctrl = next(p for p in result if p['name'] == 'controller')
        ctrl_child_names = {c['name'] for c in ctrl['children']}
        assert 'axis' not in ctrl_child_names

    def test_hardware_param_stays_at_top_level(self):
        result = _to_module_params(_flat_plugin_params())
        top_names = {p['name'] for p in result}
        assert 'com_port' in top_names

    def test_no_axis_in_plugin_no_axis_in_group(self):
        result = _to_module_params(_flat_plugin_params(with_axis=False))
        group = next(p for p in result if p['name'] == 'axis_settings')
        child_names = {c['name'] for c in group['children']}
        assert 'axis' not in child_names

    def test_bounds_children_preserved(self):
        result = _to_module_params(_flat_plugin_params())
        group = next(p for p in result if p['name'] == 'axis_settings')
        bounds = next(c for c in group['children'] if c['name'] == 'bounds')
        assert {c['name'] for c in bounds['children']} == {'is_bounds', 'min_bound', 'max_bound'}

    def test_already_grouped_passthrough(self):
        """New-style single-axis plugin params (flat axis_settings, no axis) are unchanged."""
        new_style = [
            _p('controller', children=[_p('controller_ID')]),
            _p('axis_settings', children=[_p('units'), _p('epsilon')]),
            _p('com_port'),
        ]
        result = _to_module_params(new_style)
        assert result is new_style   # exact same list object — no axis child, no upgrade needed

    def test_multiaxis_flat_old_style_creates_per_axis_groups(self):
        """Old-style multi-axis plugin params get per-axis sub-groups created."""
        result = _to_module_params(_flat_plugin_params_multiaxis(['x', 'y']))
        group = next(p for p in result if p['name'] == 'axis_settings')
        child_names = [c['name'] for c in group['children']]
        # axis selector first, then per-axis sub-groups x and y
        assert child_names[0] == 'axis'
        assert 'x' in child_names
        assert 'y' in child_names
        # Per-channel params should be inside sub-groups, not at axis_settings level
        assert 'units' not in child_names
        assert 'epsilon' not in child_names

    def test_multiaxis_per_axis_groups_have_per_channel_params(self):
        """Each per-axis sub-group inside axis_settings contains the per-channel params."""
        result = _to_module_params(_flat_plugin_params_multiaxis(['x', 'y']))
        group = next(p for p in result if p['name'] == 'axis_settings')
        x_group = next(c for c in group['children'] if c['name'] == 'x')
        x_child_names = {c['name'] for c in x_group['children']}
        assert _FLAT_PER_CHANNEL.issubset(x_child_names)

    def test_multiaxis_new_style_with_per_axis_groups_unchanged(self):
        """New-style multi-axis axis_settings already having per-axis sub-groups is unchanged."""
        new_style = [
            _p('controller', children=[_p('controller_ID')]),
            _p('axis_settings', children=[
                _p('axis', type='list', limits=['x', 'y'], value='x'),
                _p('x', children=[_p('units'), _p('epsilon')]),
                _p('y', children=[_p('units'), _p('epsilon')]),
            ]),
            _p('com_port'),
        ]
        result = _to_module_params(new_style)
        assert result is new_style   # already in new format, unchanged

    def test_does_not_mutate_input(self):
        """Original param list and dicts must not be modified."""
        original = _flat_plugin_params()
        orig_ctrl_children = list(original[0]['children'])  # copy of controller children
        _to_module_params(original)
        assert original[0]['children'] == orig_ctrl_children   # controller dict unchanged
        assert [p['name'] for p in original] == [
            'controller', 'units', 'epsilon', 'timeout', 'bounds', 'scaling', 'com_port'
        ]

    def test_empty_params(self):
        assert _to_module_params([]) == []

    def test_no_per_channel_params(self):
        """Plugin with only hardware params: no axis_settings group created."""
        params = [_p('com_port'), _p('baud_rate')]
        result = _to_module_params(params)
        assert result == params
        assert not any(p['name'] == 'axis_settings' for p in result)


class TestMapToModulePathMove:
    """DAQ_Move._map_to_module_path maps flat paths to the axis_settings layout."""

    def _map(self, path):
        # Call the unbound method directly — no Qt needed.
        return DAQ_Move._map_to_module_path(None, path)

    def test_empty_path_unchanged(self):
        assert self._map([]) == []

    def test_flat_per_channel_name_prefixed(self):
        for name in _FLAT_PER_CHANNEL:
            assert self._map([name]) == ['axis_settings', name]

    def test_flat_per_channel_nested_path_prefixed(self):
        assert self._map(['units', 'sub']) == ['axis_settings', 'units', 'sub']

    def test_controller_axis_remapped(self):
        assert self._map(['controller', 'axis']) == ['axis_settings', 'axis']

    def test_controller_axis_extra_segments_preserved(self):
        assert self._map(['controller', 'axis', 'extra']) == ['axis_settings', 'axis', 'extra']

    def test_controller_id_unchanged(self):
        assert self._map(['controller', 'controller_ID']) == ['controller', 'controller_ID']

    def test_already_grouped_unchanged(self):
        assert self._map(['axis_settings', 'units']) == ['axis_settings', 'units']

    def test_hardware_param_unchanged(self):
        assert self._map(['com_port']) == ['com_port']

    def test_hardware_nested_param_unchanged(self):
        assert self._map(['device', 'baud_rate']) == ['device', 'baud_rate']


class TestMapToModulePathBase:
    """ControllerThreadModule base returns an identity mapping (no rewriting)."""

    def _map(self, path):
        return ControllerThreadModule._map_to_module_path(None, path)

    def test_empty_path(self):
        assert self._map([]) == []

    def test_units_not_rewritten(self):
        assert self._map(['units']) == ['units']

    def test_controller_axis_not_rewritten(self):
        assert self._map(['controller', 'axis']) == ['controller', 'axis']

    def test_hardware_param_unchanged(self):
        assert self._map(['com_port']) == ['com_port']

    def test_returns_new_list(self):
        p = ['some', 'path']
        result = self._map(p)
        assert result == p
        assert result is not p
